apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: goapp-gh-240808-gitops
  description: This is GitOps manifest for goapp-gh-240808   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: goapp-gh-240808
    janus-idp.io/tekton: goapp-gh-240808
    backstage.io/kubernetes-id: goapp-gh-240808 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:goapp-gh-240808
