apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: goapp-gh-240808
  janus-idp.io/tekton: goapp-gh-240808
  backstage.io/kubernetes-id: goapp-gh-240808
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: goapp-gh-240808
resources:
- deployment.yaml
- route.yaml
- service.yaml
